name: Build and push docker image with arbitrary tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the image being built (e.g. dev). Cannot start with "v" or be "latest".'
        required: true

jobs:
  build:
    if: github.event.inputs.tag != 'latest' && !startsWith(github.event.inputs.tag, 'v')
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tugtainer
      AGENT_IMAGE_NAME: tugtainer-agent
      TAG: ${{ github.event.inputs.tag }}
    permissions:
      packages: write

    steps:
      - name: Set created datetime
        run: echo "CREATED=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push full image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.app
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            VERSION=${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=Tugtainer
            org.opencontainers.image.description=An application for automated Docker container updates with a web UI
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}
            org.opencontainers.image.created=${{ env.CREATED }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
            dev.quenary.tugtainer.protected=true

      - name: Build and push agent image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.agent
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.AGENT_IMAGE_NAME }}:${{ env.TAG }}
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ env.AGENT_IMAGE_NAME }}:${{ env.TAG }}
          build-args: |
            VERSION=${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=Tugtainer Agent
            org.opencontainers.image.description=Agent part of Tugtainer app, providing secure remote access to Docker hosts
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}
            org.opencontainers.image.created=${{ env.CREATED }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
            dev.quenary.tugtainer.protected=true
